services:
  postgresql:
    image: postgres:14.15-alpine3.21
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .postgresql.development.env

volumes:
  postgres_data: {}
